

import = [
  "~/setup/scripts/themes/active/alacritty.toml",
  "~/.config/alacritty/fonts.toml"
]
live_config_reload = true

[env]
TERM = "xterm-256color"

[window]
dynamic_title = true
dynamic_padding = true

  [window.dimensions]
  columns = 120
  lines = 30

  [window.padding]
  x = 10
  y = 10

[scrolling]
history = 10000
multiplier = 3

[cursor]
unfocused_hollow = false

  [cursor.style]
  shape = "Block"
  blinking = "On"
